spring:
  profiles:
    active: dev
    application:
      name: showcase
---
spring:
  profiles: dev

server:
  port: 8081

---
spring:
  profiles: prod

server:
  port: 8080
---
spring:
    data:
      mongodb:
        uri:mongodb://114.116.9.214:27017/RRS
---
spring:
  mail:
    host: smtp.163.com #发送邮件服务器
    username: xxq2019424@163.com #发送邮件的邮箱地址
    password: xxq2019424 #客户端授权码，不是邮箱密码,网易的是自己设置的
    from: xxq2019424@163.com # 发送邮件的地址，和上面username一致
    port: 25
    properties.smtp.starttls.enable: true
    properties.smtp.starttls.required: true
    properties.smtp.ssl.enable: true
    properties.smtp.auth: true
    default-encoding: utf-8
    propertie.mail.smtp.ssl.socketFactory: javax.net.ssl.SSLSocketFactory
---
spring:
  rabbitmq.addresses: 0.0.0.0